apiVersion: chaos-mesh.org/v1alpha1
kind: TestWickChaos
metadata:
  name: testwick-example
  namespace: chaos-mesh
spec:
  selector:
    namespaces:
      - chaos-mesh
  mode: one
  duration: 30m
testWick:
  provisionerURL: "https://provisioner.internal.test.cloud.mattermost.com"
  hostedZone: "test.mattermost.cloud"
  samples: "1"
  channelSamples: "10"
  channelMessages: "10000"
  owner: "stelios"
  size: "100users"
  affinityType: "multitenant"
  dbType: "aws-multitenant-rds-postgres-pgbouncer"
  fileStore: "bifrost"
